### ISSUE TITLE
Research Phabricator

### ISSUE THREAD

**Issue by wadebruce** [wadebruce/CD-Research#8]
Install and research Phabricator. See we can get reimbursed for AWS.

**Comment by tomitsa** [comment]
I've got this one.

**Comment by wadebruce** [comment]
Go ahead and assign it to yourself once you have your GitHub access.

I'm waiting to hear back from Sumit, but I think we'll be able to use AWS to get an instance of Phabricator.

**Comment by mdskd** [comment]
Definitely do not enable "serious business mode" when installing this tool!
